name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:    
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3        
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable     

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.x       
      
    - name: Install app dependencies
      run: npm install
           npm install @ionic/cli
           npm install ios-deploy
           npm install ios-sim
           npm install @angular/cli

    - name: Install Ionic 
      run: npm install ionic   

    - name: Pod Install      
      run: npm uninstall cocoapods -ax
           npm install cocoapods
           pod setup
    
    - name: Cap sync      
      run: ionic cap sync ios         

    - name: Build project app
      run: npm run build

    - name: Build project
      run: xcodebuild -workspace './ios/App/App.xcworkspace' -scheme App -destination generic/platform=iOS -archivePath App.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
   
